projects:
  segyio:
    color: "#859900"
    name: segyio
    repos:
      - Statoil/segyio
      - Statoil/segyviewer

  OPM:
    color: "#268bd2"
    name: Open Porous Media,
    repos:
      - OPM/opm-parser
      - OPM/opm-output

  misc:
    color: "#eac117"
    name: Other Projects
    repos:
      - Statoil/teamboard
      - Statoil/pycmake
      - Statoil/cwrap

pr_columns:
  -
    name: SegyIO
    projects:
      - segyio

  -
    name: Miscellaneous
    projects:
      - OPM
      - misc

achievements:
  -
    name: "&#x1f370;" # cake emoji
    count: 91
    since: 2017-06-01
  -
    name: "&#x1f355;&#x1f37a;" # beer and pizza emoji (cheers beer: &#x1f37b;)
    count: 191
    since: 2017-05-01

default_project_color: "#93a1a1"